# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'telaPrincipal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_telaPrincipal(object):
    def setupUi(self, telaPrincipal):
        telaPrincipal.setObjectName("telaPrincipal")
        telaPrincipal.resize(470, 270)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(telaPrincipal.sizePolicy().hasHeightForWidth())
        telaPrincipal.setSizePolicy(sizePolicy)
        telaPrincipal.setMinimumSize(QtCore.QSize(470, 270))
        telaPrincipal.setMaximumSize(QtCore.QSize(470, 270))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/logoSpike.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        telaPrincipal.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(telaPrincipal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(470, 270))
        self.centralwidget.setMaximumSize(QtCore.QSize(470, 270))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(0, 0, 0);\n"
"border: 1px solid;\n"
"    border-color: rgb(255, 0, 0);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("QFrame{\n"
"border-color: transparent;\n"
"}\n"
"QLabel{\n"
"color: rgb(255, 255, 255);\n"
"border-color: transparent;\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/icons/icons/iconChave.png"))
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"border-color: transparent;\n"
"}")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame_4)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("QFrame{\n"
"border-color: transparent;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.TXT_SENHA = QtWidgets.QLineEdit(self.frame_2)
        self.TXT_SENHA.setStyleSheet("QLineEdit{\n"
"border: 1px solid;\n"
"border-color: rgb(255, 0, 0);\n"
"}")
        self.TXT_SENHA.setObjectName("TXT_SENHA")
        self.gridLayout_3.addWidget(self.TXT_SENHA, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("QFrame{\n"
"border-color: transparent;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.BTN_SENHA = QtWidgets.QPushButton(self.frame_3)
        self.BTN_SENHA.setObjectName("BTN_SENHA")
        self.gridLayout_2.addWidget(self.BTN_SENHA, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.frame_3)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        telaPrincipal.setCentralWidget(self.centralwidget)

        self.retranslateUi(telaPrincipal)
        QtCore.QMetaObject.connectSlotsByName(telaPrincipal)

    def retranslateUi(self, telaPrincipal):
        _translate = QtCore.QCoreApplication.translate
        telaPrincipal.setWindowTitle(_translate("telaPrincipal", "Gerador de Senhas"))
        self.label_2.setText(_translate("telaPrincipal", "Gerador de Senhas"))
        self.BTN_SENHA.setText(_translate("telaPrincipal", "GERAR SENHA"))
import iconeGerador_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    telaPrincipal = QtWidgets.QMainWindow()
    ui = Ui_telaPrincipal()
    ui.setupUi(telaPrincipal)
    telaPrincipal.show()
    sys.exit(app.exec_())
